scraped_url_list = [
    # 'http://www.dejutterpurmerend.nl',
    # 'http://www.brasabarenkitchen.nl',
    # 'http://www.purmerend.family.nl',
    # 'http://spijkerman-etenendrinken.nl',
    # 'http://brasseriezomaarpurmerend.nl',
    # 'http://www.the-roast.nl',
    # 'http://www.eetcafedekeet.nl',
    # 'http://www.warrieknarrie.com',
    # 'http://www.browniesanddownies.nl',
    # 'http://www.deandereoever.nl',
    # 'http://www.bardotpurmerend.nl',
    # 'http://www.restaurantfenicie.nl',
    # 'http://www.victoriagarden.nl',
    # 'http://www.kozee-etenendrinken.nl',
    # 'http://www.lacubanita.nl',
    # 'http://brasserie1434.nl',
    # 'http://www.kritipurmerend.nl',
    # 'http://www.restauranttabasco.nl',
    # 'http://www.gachita.nl',
    # 'http://www.saporetti.nl',
    # 'http://www.deijsendijker.nl',
    # 'http://brasserie-moccano.nl',
    # 'http://www.koemarkt.com',
    # 'http://mcdonaldsrestaurant.nl',
    # 'http://purmerend.ilovesushi.nl',
    # 'http://www.reesushi.nl',
    # 'http://www.broodjeshuys.nl',
    # 'http://koffie-loket.nl',
    # 'http://www.doppio-espresso.nl',
    # 'http://www.febo.nl',
    # 'http://www.restaurantfenicie.nl',
    # 'http://www.kozee-etenendrinken.nl',
    # 'http://kwalitaria.nl',
    # 'http://bestellen.febo.nl',
    # 'http://www.lacubanita.nl',
    # 'http://www.johnnys.nl',
    # 'http://brasserie1434.nl',
    # 'http://www.kritipurmerend.nl',
    # 'http://www.gachita.nl',
    # 'http://www.restauranttabasco.nl',
    # 'http://www.saporetti.nl',
    # 'http://www.mykonospurmerend.nl',
    # 'http://www.eterijeffeanders.nl',
    # 'http://www.eetcafejoenco.nl',
    # 'http://www.victoriagarden.nl',
    # 'http://restauranttwaalf.nl',
    # 'http://restaurantdedoele.nl',
    # 'http://www.restaurantlacasa.nl',
    # 'http://www.lemon-leaf.nl',
    # 'http://restaurants.subway.com',
    # 'http://www.hoedjevandekoningin.nl',
    # 'http://etenbijrozemeijer.nl',
    'http://www.cafedeheeren.nl',
    'http://www.smidetenendrinken.nl',
    'http://www.de-stallen.nl',
    'http://www.tbeste.nl',
    'http://www.sensosushi.nl',
    'http://diwalirestaurant.nl',
    'http://www.mr-miyagi.nl',
    'http://arabesque-streetfood.nl',
    'http://bluelotus.foodticket.nl',
    'http://www.montegrandi.com',
    'http://www.facebook.com',
    'http://chineesrestaurantazie.nl',
    'http://www.ferids.nl',
    'http://holy-grill.nl',
    'http://www.caferooiesien.nl',
    'http://www.putrisolo.nl',
    'http://www.yatta-orient.nl',
    'http://www.kfc.nl',
    'http://www.bnbbardot.nl',
    'http://www.vishandelsierpurmerend.nl',
    'http://www.midorikawa.nl',
    'http://www.saricitra.nl',
    'http://www.shoarma-babylon.nl',
    'http://cuisine-culinaire-purmerend.nl',
    'http://www.yatta-orient.nl',
    'http://www.nerone.nl',
    'http://www.thaisebezorglijn.nl',
    'http://www.kamlin.nl',
    'http://www.kapadokya-purmerend.nl',
    'http://brunchroombliss.nl',
    'http://www.troyadoner.nl',
    'http://www.goldendoner.nl',
    'http://www.donerplaza-purmerend.nl',
    'http://www.burggolf.nl',
    'http://www.pizza-cleopatra.nl',
    'http://www.italia-pizzeria.nl'
]