dict_list = [
    {'website': 'http://www.the-roast.nl', 'emails': {'sales@the-roast.nl', 'info@the-roast.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.lacubanita.nl', 'emails': {'emmen@lacubanita.nl', 'tilburg@lacubanita.nl', 'zwolle@lacubanita.nl', 'alkmaar@lacubanita.nl', 'bussum@lacubanita.nl', 'apeldoorn@lacubanita.nl', 'amersfoort@lacubanita.nl', 'nieuwegein@lacubanita.nl', 'voorburg@lacubanita.nl', 'noordwijk@lacubanita.nl', 'utrecht@lacubanita.nl', 'hoofddorp@lacubanita.nl', 'haarlem@lacubanita.nl', 'zaandam@lacubanita.nl', 'leiden@lacubanita.nl', 'ridderkerk@lacubanita.nl', 'enschede@lacubanita.nl', 'rotterdam@lacubanita.nl', 'denhelder@lacubanita.nl', 'denhaag@lacubanita.nl', 'heerlen@lacubanita.nl', 'almere@lacubanita.nl', 'spijkenisse@lacubanita.nl', 'maastricht@lacubanita.nl', 'purmerend@lacubanita.nl', 'hoorn@lacubanita.nl', 'helmond@lacubanita.nl', 'sittard@lacubanita.nl', 'shertogenbosch@lacubanita.nl', 'roosendaal@lacubanita.nl', 'weert@lacubanita.nl', 'beverwijk@lacubanita.nl', 'tiel@lacubanita.nl', 'eindhoven@lacubanita.nl', 'groningen@lacubanita.nl', 'info@lacubanita.nl', 'heerhugowaard@lacubanita.nl', 'delft@lacubanita.nl', 'breda@lacubanita.nl', 'harderwijk@lacubanita.nl', 'deventer@lacubanita.nl', 'schiedam@lacubanita.nl', 'nijmegen@lacubanita.nl', 'zoetermeer@lacubanita.nl', 'leeuwarden@lacubanita.nl', 'arnhem@lacubanita.nl', 'doetinchem@lacubanita.nl', 'schagen@lacubanita.nl', 'gorinchem@lacubanita.nl', 'gouda@lacubanita.nl', 'woerden@lacubanita.nl', 'dordrecht@lacubanita.nl', 'alphen@lacubanita.nl', 'naaldwijk@lacubanita.nl'}, 'level': 'sure', 'contacturl': 'https://lacubanita.nl/contact'},
    {'website': 'http://www.lacubanita.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.dejutterpurmerend.nl', 'emails': {'info@dejutterpurmerend.nl', 'solliciteren@dejutterpurmerend.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.kozee-etenendrinken.nl', 'emails': {'info@kozee-etenendrinken.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.brasabarenkitchen.nl', 'emails': {'info@brasapurmerend.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.restaurantfenicie.nl', 'emails': {'purmerend@fenicie.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.restauranttabasco.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.restauranttabasco.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://brasserie1434.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'https://brasserie1434.nl/over-brasserie-1434/'},
    {'website': 'http://brasserie1434.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.saporetti.nl', 'emails': {'info@saporetti.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.gachita.nl', 'emails': {'info@gachita.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.victoriagarden.nl', 'emails': {'victoriagarden2006@hotmail.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.mykonospurmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.mykonospurmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.eterijeffeanders.nl', 'emails': {'info@eterijeffeanders.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://restaurantdedoele.nl', 'emails': {'info@wokdedoele.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.restaurantlacasa.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://restaurantlacasa.nl/en/direct-contact-met-la-casa/'}   ,
    {'website': 'http://www.restaurantlacasa.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.kritipurmerend.nl', 'emails': {'kritireserveren@gmail.com'}, 'level': 'sure', 'contacturl': 'http://www.kritipurmerend.nl/contact'},
    {'website': 'http://www.kritipurmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.the-roast.nl', 'emails': {'sales@the-roast.nl', 'info@the-roast.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.purmerend.family.nl', 'emails': {'rongwei718@hotmail.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://spijkerman-etenendrinken.nl', 'emails': {'info@spijkerman-etenendrinken.nl'}, 'level': 'sure', 'contacturl': 'http://spijkerman-etenendrinken.nl/contact'}    ,
    {'website': 'http://spijkerman-etenendrinken.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.cafedeheeren.nl', 'emails': {'info@cafedeheeren.nl', 'contact@example.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.eetcafejoenco.nl', 'emails': {'info@eetcafejoenco.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.the-roast.nl', 'emails': {'sales@the-roast.nl', 'info@the-roast.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.eetcafedekeet.nl', 'emails': {'info@dekeetpurmerend.nl', 'dekeetpurmerend@gmail.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.de-stallen.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'https://www.de-stallen.nl/over-ons/'},
    {'website': 'http://www.de-stallen.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.sensosushi.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.sensosushi.nl/over-senso'},
    {'website': 'http://www.sensosushi.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://diwalirestaurant.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://diwalirestaurant.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://arabesque-streetfood.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://arabesque-streetfood.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.purmerend.family.nl', 'emails': {'rongwei718@hotmail.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.mr-miyagi.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.mr-miyagi.nl/contact'},
    {'website': 'http://www.mr-miyagi.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.bardotpurmerend.nl', 'emails': {'hello@bnbbardot.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://bluelotus.foodticket.nl', 'emails': {'info@bluelotus.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.facebook.com', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': '/recover/initiate/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjgyMjY5NDEzLCJjYWxsc2l0ZV9pZCI6Mjg0Nzg1MTQ5MzQ1MzY5fQ%3D%3D&c=https%3A%2F%2Fm.facebook.com%2F&r&cuid&ars=facebook_login&lwv=100&refid=8'},
    {'website': 'http://www.facebook.com', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://chineesrestaurantazie.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://chineesrestaurantazie.nl/contact'},
    {'website': 'http://chineesrestaurantazie.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.browniesanddownies.nl', 'emails': {'8c4075d5481d476e945486754f783364@sentry.io', '605a7baede844d278b89dc95ae0a9123@sentry-next.wixpress.com', '8eb368c655b84e029ed79ad7a5c1718e@sentry.wixpress.com', 'dd0a55ccb8124b9c9d938e3acf41f8aa@sentry.wixpress.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.ferids.nl', 'emails': {'klod_83@hotmail.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://holy-grill.nl', 'emails': {'info@holy-grill.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.caferooiesien.nl', 'emails': {'info@caferooiesien.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.yatta-orient.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.yatta-orient.nl/contact'},
    {'website': 'http://www.yatta-orient.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.burggolf.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'https://www.burggolf.nl/nieuws-overzicht/'},
    {'website': 'http://www.burggolf.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.febo.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.febo.nl/contact/veelgestelde-vragen/'},
    {'website': 'http://www.febo.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.midorikawa.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.midorikawa.nl/contact'},
    {'website': 'http://www.midorikawa.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.cafedebalustrade.nl', 'emails': {'info@cafedebalustrade.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://staeky.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'https://staeky.nl/over-ons/'},
    {'website': 'http://staeky.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.shoarma-babylon.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.shoarma-babylon.nl#business-contact-info'},
    {'website': 'http://www.shoarma-babylon.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.saricitra.nl', 'emails': {'saricitra52@gmail.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.koemarkt.com', 'emails': {'contact@example.com'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://cuisine-culinaire-purmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'https://cuisine-culinaire-purmerend.nl/over-ons/'}     ,
    {'website': 'http://cuisine-culinaire-purmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.yatta-orient.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.yatta-orient.nl/contact'},
    {'website': 'http://www.yatta-orient.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.nerone.nl', 'emails': {'contact@nerone.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.kamlin.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.kamlin.nl/contact-en-route'},
    {'website': 'http://www.kamlin.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.thaisebezorglijn.nl', 'emails': {'info@thaisebezorglijn.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.reesushi.nl', 'emails': {'info@reesushi.nl'}, 'level': 'sure', 'contacturl': ''},
    {'website': 'http://www.kapadokya-purmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': 'http://www.kapadokya-purmerend.nl/contact'},
    {'website': 'http://www.kapadokya-purmerend.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.goldendoner.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.goldendoner.nl', 'emails': {'info@Troyadoner.nl'}, 'level': 'not sure', 'contacturl': ''},
    {'website': 'http://www.troyadoner.nl', 'emails': {'troyapurmerend@gmail.com'}, 'level': 'sure', 'contacturl': ''},
]