import csv


class WriteCsv:
    '''
    Write email data dicts to mails.csv with with header and footer
    Header includes keywords and rows
    Footer includes credits to Me
    Nothing stored nothing returned
    '''
    def __init__(self, dict_list: list, keywords: str):
        self.dict_list = dict_list
        self.keywords = keywords
        
        self.FIELDNAMES = ['website', 'emails', 'level', 'contacturl']
        
        self.Openandwrite()
        
    
    def Writeheader(self, writer: object, f: object) -> None:
        ''' Write csv header with keywords '''
        writer.writerow({'website': 'Keywords used', 'emails': self.keywords})
        writer.writeheader()
        f.write('\n')
        
    
    def Writebody(self, writer: object) -> None:   
        ''' Write all the data from the script in the csv file '''        
        for data in self.dict_list:
            email_string = ', '.join(data['emails'])
            data['emails'] = email_string
            writer.writerow(data)
            
    def Writefooter(self, writer: object, f: object) -> None:
        ''' Write footer with credits to akula_Arthur '''
        f.write('\n')
        f.write('\n')
        
        writer.writerow({'website': 'automatically generated by OOP mail v2'})
        writer.writerow({'website': 'Made by akula_Arthur'})

    def Openandwrite(self) -> None:
        ''' Open mails.csv and write header, body, and footer data to csv '''
        with open('mails.csv', 'a', encoding='UTF-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=self.FIELDNAMES)
            
            self.Writeheader(writer, f)
            self.Writebody(writer)
            self.Writefooter(writer, f)
            
            
                
            