import csv


class WriteCsv:
    def __init__(self, dict_list, keywords):
        self.dict_list = dict_list
        self.keywords = keywords
        
        self.FIELDNAMES = ['website', 'emails', 'level', 'contacturl']
        
        self.Openandwrite()
        
    
    def Writeheader(self, writer, f):
        writer.writerow({'website': 'Keywords used', 'emails': self.keywords})
        writer.writeheader()
        f.write('\n')
        
    
    def Writebody(self, writer):            
        for data in self.dict_list:
            email_string = ', '.join(data['emails'])
            data['emails'] = email_string
            writer.writerow(data)
            
    def Writefooter(self, writer, f):
        f.write('\n')
        f.write('\n')
        
        writer.writerow({'website': 'automatically generated by OOP mail v2'})
        writer.writerow({'website': 'Made by akula_Arthur'})

    def Openandwrite(self):
        with open('mails.csv', 'a', encoding='UTF-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=self.FIELDNAMES)
            
            self.Writeheader(writer, f)
            self.Writebody(writer)
            self.Writefooter(writer, f)
            
            
                
            